export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const PRODUCT_DELETED_SUCCESS = "PRODUCT_DELETED_SUCCESS";
export const PRODUCT_DELETED_ERROR = "PRODUCT_DELETED_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_PRODUCT_EDITION = "START_PRODUCT_EDITION";
export const PRODUCT_EDITED_SUCCESS = "PRODUCT_EDITED_SUCCESS";
export const PRODUCT_EDITED_ERROR = "PRODUCT_EDITED_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
